package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u5f00\u95f8\u7eaa\u5f55\uff0c\u76f8\u673a\u5f00\u95f8\u540e\u4e0a\u62a5\u7684\u5f00\u95f8\u7eaa\u5f55<br>
 * <i>native declaration : config_gw.h:1185</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AlarmInfoRecord extends Structure {
	/**
	 * \u76f8\u673a\u7f16\u53f7<br>
	 * C type : char[32]
	 */
	public byte[] cameraID = new byte[32];
	/**
	 * \u5f00\u95f8\u65f6\u95f4     \u683c\u5f0f\uff1a2018/3/6    16:38:20<br>
	 * C type : char[20]
	 */
	public byte[] alarmTime = new byte[20];
	/** \u5f00\u95f8\u8bbe\u5907\u7c7b\u578b\uff0c0\uff1a\u7ee7\u7535\u5668 1\uff1a\u97e6\u6839\u8bbe\u5907 */
	public byte alarmDeviceType;
	/**
	 * \u4fdd\u7559<br>
	 * C type : char[3]
	 */
	public byte[] resv = new byte[3];
	/**
	 * \u4eba\u5458id\uff0c\u62a5\u8b66\u5f00\u95f8\u7684\u4eba\u5458id<br>
	 * C type : char[20]
	 */
	public byte[] personID = new byte[20];
	/** \u5f00\u95f8\u8bbe\u5907id\uff0c\u5916\u8bbe\u7c7b\u578b\u4e3a\u7ee7\u7535\u5668\u65f6\uff0c\u5916\u8bbeID\u4e3aGPIO\u7aef\u53e3\u53f7\u3002\u5916\u8bbe\u7c7b\u578b\u4e3a\u652f\u6301\u97e6\u6839\u534f\u8bae\u7684\u8bbe\u5907\u65f6\uff0c\u5916\u8bbeID\u4e3a\u5361\u53f7\u3002 */
	public int alarmDeviceId;
	public AlarmInfoRecord() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("cameraID", "alarmTime", "alarmDeviceType", "resv", "personID", "alarmDeviceId");
	}
	/**
	 * @param cameraID \u76f8\u673a\u7f16\u53f7<br>
	 * C type : char[32]<br>
	 * @param alarmTime \u5f00\u95f8\u65f6\u95f4     \u683c\u5f0f\uff1a2018/3/6    16:38:20<br>
	 * C type : char[20]<br>
	 * @param alarmDeviceType \u5f00\u95f8\u8bbe\u5907\u7c7b\u578b\uff0c0\uff1a\u7ee7\u7535\u5668 1\uff1a\u97e6\u6839\u8bbe\u5907<br>
	 * @param resv \u4fdd\u7559<br>
	 * C type : char[3]<br>
	 * @param personID \u4eba\u5458id\uff0c\u62a5\u8b66\u5f00\u95f8\u7684\u4eba\u5458id<br>
	 * C type : char[20]<br>
	 * @param alarmDeviceId \u5f00\u95f8\u8bbe\u5907id\uff0c\u5916\u8bbe\u7c7b\u578b\u4e3a\u7ee7\u7535\u5668\u65f6\uff0c\u5916\u8bbeID\u4e3aGPIO\u7aef\u53e3\u53f7\u3002\u5916\u8bbe\u7c7b\u578b\u4e3a\u652f\u6301\u97e6\u6839\u534f\u8bae\u7684\u8bbe\u5907\u65f6\uff0c\u5916\u8bbeID\u4e3a\u5361\u53f7\u3002
	 */
	public AlarmInfoRecord(byte cameraID[], byte alarmTime[], byte alarmDeviceType, byte resv[], byte personID[], int alarmDeviceId) {
		super();
		if ((cameraID.length != this.cameraID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.cameraID = cameraID;
		if ((alarmTime.length != this.alarmTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.alarmTime = alarmTime;
		this.alarmDeviceType = alarmDeviceType;
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
		if ((personID.length != this.personID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.personID = personID;
		this.alarmDeviceId = alarmDeviceId;
	}
	public static class ByReference extends AlarmInfoRecord implements Structure.ByReference {
		
	};
	public static class ByValue extends AlarmInfoRecord implements Structure.ByValue {
		
	};
}
