package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u5f00\u95f8\u8bf7\u6c42\uff0c\u5f53\u76f8\u673a\u5904\u4e8e\u5728\u7ebf\u6a21\u5f0f\u65f6\uff0c\u9700\u8981\u5f00\u95f8\u65f6\u4f1a\u5411\u5e73\u53f0\u53d1\u9001\u8be5\u8bf7\u6c42<br>
 * <i>native declaration : config_gw.h:1196</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AlarmRequest extends Structure {
	/**
	 * \u76f8\u673a\u7f16\u53f7<br>
	 * C type : char[32]
	 */
	public byte[] cameraID = new byte[32];
	/**
	 * \u4eba\u5458id\uff0c\u9700\u8981\u5f00\u95f8\u7684\u4eba\u5458id<br>
	 * C type : char[20]
	 */
	public byte[] personID = new byte[20];
	/**
	 * \u8bf7\u6c42\u65f6\u95f4     \u683c\u5f0f\uff1a2018/3/6    16:38:20<br>
	 * C type : char[20]
	 */
	public byte[] requestTime = new byte[20];
	/** \u8bf7\u6c42\u7684\u5f00\u95f8\u8bbe\u5907\u7c7b\u578b\uff0c0\uff1a\u7ee7\u7535\u5668 1\uff1a\u97e6\u6839\u8bbe\u5907 */
	public byte alarmDeviceType;
	/** \u5f53\u524d\u5f00\u95f8\u8bbe\u5907\u72b6\u6001\uff0c0\uff1a\u672a\u542f\u7528 1\uff1a\u542f\u7528 */
	public byte alarmDeviceState;
	/**
	 * \u4fdd\u7559<br>
	 * C type : char[2]
	 */
	public byte[] resv = new byte[2];
	/** \u5f00\u95f8\u8bbe\u5907id\uff0c\u5916\u8bbe\u7c7b\u578b\u4e3a\u7ee7\u7535\u5668\u65f6\uff0c\u5916\u8bbeID\u4e3aGPIO\u7aef\u53e3\u53f7\u3002\u5916\u8bbe\u7c7b\u578b\u4e3a\u652f\u6301\u97e6\u6839\u534f\u8bae\u7684\u8bbe\u5907\u65f6\uff0c\u5916\u8bbeID\u4e3a\u5361\u53f7\u3002 */
	public int alarmDeviceId;
	public AlarmRequest() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("cameraID", "personID", "requestTime", "alarmDeviceType", "alarmDeviceState", "resv", "alarmDeviceId");
	}
	/**
	 * @param cameraID \u76f8\u673a\u7f16\u53f7<br>
	 * C type : char[32]<br>
	 * @param personID \u4eba\u5458id\uff0c\u9700\u8981\u5f00\u95f8\u7684\u4eba\u5458id<br>
	 * C type : char[20]<br>
	 * @param requestTime \u8bf7\u6c42\u65f6\u95f4     \u683c\u5f0f\uff1a2018/3/6    16:38:20<br>
	 * C type : char[20]<br>
	 * @param alarmDeviceType \u8bf7\u6c42\u7684\u5f00\u95f8\u8bbe\u5907\u7c7b\u578b\uff0c0\uff1a\u7ee7\u7535\u5668 1\uff1a\u97e6\u6839\u8bbe\u5907<br>
	 * @param alarmDeviceState \u5f53\u524d\u5f00\u95f8\u8bbe\u5907\u72b6\u6001\uff0c0\uff1a\u672a\u542f\u7528 1\uff1a\u542f\u7528<br>
	 * @param resv \u4fdd\u7559<br>
	 * C type : char[2]<br>
	 * @param alarmDeviceId \u5f00\u95f8\u8bbe\u5907id\uff0c\u5916\u8bbe\u7c7b\u578b\u4e3a\u7ee7\u7535\u5668\u65f6\uff0c\u5916\u8bbeID\u4e3aGPIO\u7aef\u53e3\u53f7\u3002\u5916\u8bbe\u7c7b\u578b\u4e3a\u652f\u6301\u97e6\u6839\u534f\u8bae\u7684\u8bbe\u5907\u65f6\uff0c\u5916\u8bbeID\u4e3a\u5361\u53f7\u3002
	 */
	public AlarmRequest(byte cameraID[], byte personID[], byte requestTime[], byte alarmDeviceType, byte alarmDeviceState, byte resv[], int alarmDeviceId) {
		super();
		if ((cameraID.length != this.cameraID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.cameraID = cameraID;
		if ((personID.length != this.personID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.personID = personID;
		if ((requestTime.length != this.requestTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.requestTime = requestTime;
		this.alarmDeviceType = alarmDeviceType;
		this.alarmDeviceState = alarmDeviceState;
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
		this.alarmDeviceId = alarmDeviceId;
	}
	public static class ByReference extends AlarmRequest implements Structure.ByReference {
		
	};
	public static class ByValue extends AlarmRequest implements Structure.ByValue {
		
	};
}
