package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u5e94\u7528\u7a0b\u5e8f\u53c2\u6570(1024\u5b57\u8282)\u3002<br>
 * <i>native declaration : config_gw.h:896</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AppParam extends Structure {
	/**
	 * \u5404\u5e94\u7528\u7a0b\u5e8f\u516c\u7528\u53c2\u6570\u3002<br>
	 * C type : AppCommonParam
	 */
	public AppCommonParam common;
	/**
	 * \u79c1\u6709\u53c2\u6570\u3002<br>
	 * C type : AppPrivateParam
	 */
	public AppPrivateParam priv;
	public AppParam() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("common", "priv");
	}
	/**
	 * @param common \u5404\u5e94\u7528\u7a0b\u5e8f\u516c\u7528\u53c2\u6570\u3002<br>
	 * C type : AppCommonParam<br>
	 * @param priv \u79c1\u6709\u53c2\u6570\u3002<br>
	 * C type : AppPrivateParam
	 */
	public AppParam(AppCommonParam common, AppPrivateParam priv) {
		super();
		this.common = common;
		this.priv = priv;
	}
	public static class ByReference extends AppParam implements Structure.ByReference {
		
	};
	public static class ByValue extends AppParam implements Structure.ByValue {
		
	};
}
