package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u7cfb\u7edf\u5e94\u7528\u79c1\u6709\u53c2\u6570\u3002<br>
 * <i>native declaration : config_gw.h:782</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AppPrivateParam extends Structure {
	/**
	 * \u5404\u7cfb\u7edf\u81ea\u884c\u5b9a\u4e49\u3002<br>
	 * C type : char[512]
	 */
	public byte[] resv = new byte[512];
	public AppPrivateParam() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("resv");
	}
	/**
	 * @param resv \u5404\u7cfb\u7edf\u81ea\u884c\u5b9a\u4e49\u3002<br>
	 * C type : char[512]
	 */
	public AppPrivateParam(byte resv[]) {
		super();
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
	}
	public static class ByReference extends AppPrivateParam implements Structure.ByReference {
		
	};
	public static class ByValue extends AppPrivateParam implements Structure.ByValue {
		
	};
}
