package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u670d\u52a1\uff0832\u5b57\u8282\uff09\u3002<br>
 * <i>native declaration : config_gw.h:751</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AppServicesParam extends Structure {
	/**
	 * \u914d\u7f6e\u670d\u52a1\u3002<br>
	 * C type : ServiceParam
	 */
	public ServiceParam config_service;
	/**
	 * \u67e5\u8be2\u670d\u52a1\u3002<br>
	 * C type : ServiceParam
	 */
	public ServiceParam query_service;
	/**
	 * \u65e5\u5fd7\u670d\u52a1\u3002<br>
	 * C type : ServiceParam
	 */
	public ServiceParam log_service;
	/**
	 * \u4fdd\u7559\u3002<br>
	 * C type : ServiceParam
	 */
	public ServiceParam resv_service;
	public AppServicesParam() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("config_service", "query_service", "log_service", "resv_service");
	}
	/**
	 * @param config_service \u914d\u7f6e\u670d\u52a1\u3002<br>
	 * C type : ServiceParam<br>
	 * @param query_service \u67e5\u8be2\u670d\u52a1\u3002<br>
	 * C type : ServiceParam<br>
	 * @param log_service \u65e5\u5fd7\u670d\u52a1\u3002<br>
	 * C type : ServiceParam<br>
	 * @param resv_service \u4fdd\u7559\u3002<br>
	 * C type : ServiceParam
	 */
	public AppServicesParam(ServiceParam config_service, ServiceParam query_service, ServiceParam log_service, ServiceParam resv_service) {
		super();
		this.config_service = config_service;
		this.query_service = query_service;
		this.log_service = log_service;
		this.resv_service = resv_service;
	}
	public static class ByReference extends AppServicesParam implements Structure.ByReference {
		
	};
	public static class ByValue extends AppServicesParam implements Structure.ByValue {
		
	};
}
