package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : HASdkDef.h:262</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AudioItem extends Structure {
	public int id;
	/** C type : char[64] */
	public byte[] desc = new byte[64];
	public AudioItem() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("id", "desc");
	}
	/** @param desc C type : char[64] */
	public AudioItem(int id, byte desc[]) {
		super();
		this.id = id;
		if ((desc.length != this.desc.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.desc = desc;
	}
	public static class ByReference extends AudioItem implements Structure.ByReference {
		
	};
	public static class ByValue extends AudioItem implements Structure.ByValue {
		
	};
}
