package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u76f8\u673a\u53c2\u6570(512\u5b57\u8282)\u3002<br>
 * <i>native declaration : config_gw.h:696</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CameraParam extends Structure {
	/**
	 * \u76f8\u673a\u6d41\u540d\u79f0\u3002<br>
	 * C type : char[128]
	 */
	public byte[] stream_url = new byte[128];
	/** \u76f8\u673a\u6d41\u7aef\u53e3\u3002 */
	public short stream_port;
	/** \u76f8\u673a\u63a7\u5236\u7aef\u53e3\u3002 */
	public short control_port;
	/**
	 * \u89c6\u9891OSD\uff0c\u652f\u6301\u6700\u591a\u4e24\u884c\u3002<br>
	 * C type : char[2][96]
	 */
	public byte[] video_osd = new byte[((2) * (96))];
	/** \u5e27\u7387\u3002 */
	public byte fps;
	/** \u9971\u548c\u5ea6\u3002\u53d6\u503c\u8303\u56f4\uff1a1~255\u3002 */
	public byte saturation;
	/** \u4eae\u5ea6\u3002\u53d6\u503c\u8303\u56f4\uff1a1~100\u3002 */
	public byte brightness;
	/** \u81ea\u52a8\u66dd\u5149\u4f7f\u80fd\u5f00\u5173\u3002 */
	public byte enable_ae;
	/** \u6700\u5927\u66dd\u5149\u65f6\u95f4\u3002\u5355\u4f4d\uff1a\u6beb\u79d2\u3002\u53d6\u503c\u8303\u56f4\uff1a0~100\u3002 */
	public short max_exposure;
	/** \u6700\u5927\u589e\u76ca\u3002\u5355\u4f4d\uff1aDB\u3002\u53d6\u503c\u8303\u56f4\uff1a0~40\u3002 */
	public short max_gain;
	/** \u5bf9\u6bd4\u5ea6\u3002\u53d6\u503c\u8303\u56f4\uff1a0~128\u3002 */
	public short contrast;
	/** \u7801\u7387\u3002\u5355\u4f4d\uff1akbps\u3002 */
	public short video_br;
	/** \u89c6\u9891\u6d41\u56fe\u50cf\u5bbd\u5ea6\u3002 */
	public short video_width;
	/** \u89c6\u9891\u6d41\u56fe\u50cf\u9ad8\u5ea6\u3002 */
	public short video_height;
	/** \u89c6\u9891\u6d41\u7f16\u7801\u7c7b\u578b\u30021\uff1aH264\uff0c2\uff1aMJPEG\u3002 */
	public byte video_enc_type;
	/** \u89c6\u9891\u65cb\u8f6c\u89d2\u5ea6\u3002 0:\u9ed8\u8ba4\u503c 1\uff1a\u987a\u65f6\u9488\u65cb\u8f6c90\u5ea6 2\uff1a\u987a\u65f6\u9488\u65cb\u8f6c180\u5ea6 3\uff1a\u987a\u65f6\u9488\u65cb\u8f6c270\u5ea6\u3002 */
	public byte video_rotate;
	/**
	 * \u4fdd\u7559\u3002<br>
	 * C type : char[170]
	 */
	public byte[] resv = new byte[170];
	public CameraParam() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("stream_url", "stream_port", "control_port", "video_osd", "fps", "saturation", "brightness", "enable_ae", "max_exposure", "max_gain", "contrast", "video_br", "video_width", "video_height", "video_enc_type", "video_rotate", "resv");
	}
	public static class ByReference extends CameraParam implements Structure.ByReference {
		
	};
	public static class ByValue extends CameraParam implements Structure.ByValue {
		
	};
}
