package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u7528\u6765\u914d\u7f6e\u67d0\u4e2ainput io\u7684\u5177\u4f53\u5c5e\u6027<br>
 * <i>native declaration : config_gw.h:212</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class coil_io_attr extends Structure {
	/** \u6240\u5c5e\u7ebf\u5708\u7684\u7ec4\u53f7(\u8f66\u9053\u53f7) < MAX_COIL_GROUP */
	public byte group;
	/** \u5c5e\u4e8e\u8be5\u7ec4\u7ebf\u5708\u7684\u7b2c\u51e0\u4e2aIO\u4fe1\u53f7 0 or 1 */
	public byte index;
	/** \u89e6\u53d1\u591a\u5c11\u5f20 <= 2 */
	public byte count;
	/** \u95ea\u5149\u706f\u5173\u8054\uff0c\u4f4e\u56db\u4f4d\u6bcf\u4e00\u4f4d(=1)\u8868\u793a\u5173\u8054\u8be5\u8def\u95ea\u5149\u706f */
	public byte match_light;
	public coil_io_attr() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("group", "index", "count", "match_light");
	}
	/**
	 * @param group \u6240\u5c5e\u7ebf\u5708\u7684\u7ec4\u53f7(\u8f66\u9053\u53f7) < MAX_COIL_GROUP<br>
	 * @param index \u5c5e\u4e8e\u8be5\u7ec4\u7ebf\u5708\u7684\u7b2c\u51e0\u4e2aIO\u4fe1\u53f7 0 or 1<br>
	 * @param count \u89e6\u53d1\u591a\u5c11\u5f20 <= 2<br>
	 * @param match_light \u95ea\u5149\u706f\u5173\u8054\uff0c\u4f4e\u56db\u4f4d\u6bcf\u4e00\u4f4d(=1)\u8868\u793a\u5173\u8054\u8be5\u8def\u95ea\u5149\u706f
	 */
	public coil_io_attr(byte group, byte index, byte count, byte match_light) {
		super();
		this.group = group;
		this.index = index;
		this.count = count;
		this.match_light = match_light;
	}
	public static class ByReference extends coil_io_attr implements Structure.ByReference {
		
	};
	public static class ByValue extends coil_io_attr implements Structure.ByValue {
		
	};
}
