package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u8bc6\u522b\u53c2\u6570\u7684\u914d\u7f6e\u3001\u6821\u9a8c\u3001\u91cd\u7f6e *****<br>
 * <i>native declaration : config_gw.h:349</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class config_reco extends Structure {
	public int enable;
	public float ratio;
	/** C type : char[16] */
	public byte[] province = new byte[16];
	public short min_width;
	public short max_width;
	/** C type : config_rect[(4)] */
	public config_rect[] reco_area = new config_rect[4];
	/** \u5728\u8bc6\u522b\u7ed3\u679c\u4e0a\u753b\u51fa\u8bc6\u522b\u533a\u57df */
	public int draw_reco_area;
	public int filter_color;
	public int filter_num;
	/** \u76f8\u540c\u8f66\u724c\u4e0a\u62a5\u95f4\u9694\uff0c\u5355\u4f4d:\u79d2 */
	public short same_plate_report_time;
	public byte draw_reco_area_video;
	/** 0,1\u4e3a\u6b63\u5e38\u89d2\u5ea6\uff0c2\u4e3a\u81ea\u52a8\uff0c3\u4e3a\u5927\u89d2\u5ea6 */
	public byte reco_mode;
	/** C type : char[48] */
	public byte[] resv = new byte[48];
	public config_reco() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enable", "ratio", "province", "min_width", "max_width", "reco_area", "draw_reco_area", "filter_color", "filter_num", "same_plate_report_time", "draw_reco_area_video", "reco_mode", "resv");
	}
	public static class ByReference extends config_reco implements Structure.ByReference {
		
	};
	public static class ByValue extends config_reco implements Structure.ByValue {
		
	};
}
