package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : config_gw.h:625</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class config_gateway extends Structure {
	public int magic_number;
	/** C type : config_worktime */
	public config_worktime worktime;
	/** C type : config_addr */
	public config_addr addr;
	/** C type : config_reco */
	public config_reco reco;
	/** C type : config_limit_speed */
	public config_limit_speed limit_speed;
	/** C type : config_radar */
	public config_radar radar;
	/** C type : config_coil */
	public config_coil coil;
	/** C type : config_special */
	public config_special special;
	/** C type : config_net */
	public config_net net;
	/** C type : config_face_detect */
	public config_face_detect face;
	/** C type : config_vdetect */
	public config_vdetect vdetect;
	/** C type : config_people_red */
	public config_people_red people_red;
	/**
	 * \u505c\u8f66\u573a\u76f8\u5173\u914d\u7f6e<br>
	 * C type : config_gw_park
	 */
	public config_gw_park park;
	/**
	 * \u8f66\u4f4d\u76f8\u673a\u76f8\u5173\u914d\u7f6e<br>
	 * C type : config_gw_car_port
	 */
	public config_gw_car_port carpos;
	/** C type : config_http */
	public config_http http;
	/** C type : config_device_group */
	public config_device_group device_group;
	public config_gateway() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("magic_number", "worktime", "addr", "reco", "limit_speed", "radar", "coil", "special", "net", "face", "vdetect", "people_red", "park", "carpos", "http", "device_group");
	}
	public static class ByReference extends config_gateway implements Structure.ByReference {
		
	};
	public static class ByValue extends config_gateway implements Structure.ByValue {
		
	};
}
