package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u8f66\u4f4d\u4fe1\u606f<br>
 * <i>native declaration : config_gw.h:531</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class config_carbinet extends Structure {
	/** \u662f\u5426\u7279\u6b8a\u8f66\u4f4d 0\u4e00\u822c\u8f66\u4f4d 1\u7279\u6b8a\u8f66\u4f4d */
	public int isSpecial;
	/** \u8f66\u4f4d\u53f7 */
	public int portNum;
	public config_carbinet() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("isSpecial", "portNum");
	}
	/**
	 * @param isSpecial \u662f\u5426\u7279\u6b8a\u8f66\u4f4d 0\u4e00\u822c\u8f66\u4f4d 1\u7279\u6b8a\u8f66\u4f4d<br>
	 * @param portNum \u8f66\u4f4d\u53f7
	 */
	public config_carbinet(int isSpecial, int portNum) {
		super();
		this.isSpecial = isSpecial;
		this.portNum = portNum;
	}
	public static class ByReference extends config_carbinet implements Structure.ByReference {
		
	};
	public static class ByValue extends config_carbinet implements Structure.ByValue {
		
	};
}
