package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : config_gw.h:569</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class config_http extends Structure {
	/** C type : char[20] */
	public byte[] http_ip = new byte[20];
	public short http_port;
	public short ssl_port;
	public int timeout;
	public byte enable_ssl;
	public byte enable_reg;
	public byte enable_post_vehicle;
	public byte enable_img;
	public byte enable_plate_img;
	public byte enable_post_io_info;
	public byte enable_post_serial_data;
	public byte vehicle_level;
	/** C type : char[96] */
	public byte[] reg_url = new byte[96];
	/** C type : char[96] */
	public byte[] post_vehicle_url = new byte[96];
	/** C type : char[96] */
	public byte[] post_ioinfo_url = new byte[96];
	/** C type : char[96] */
	public byte[] post_serial_url = new byte[96];
	/** C type : unsigned char[128] */
	public byte[] resv = new byte[128];
	public config_http() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("http_ip", "http_port", "ssl_port", "timeout", "enable_ssl", "enable_reg", "enable_post_vehicle", "enable_img", "enable_plate_img", "enable_post_io_info", "enable_post_serial_data", "vehicle_level", "reg_url", "post_vehicle_url", "post_ioinfo_url", "post_serial_url", "resv");
	}
	public static class ByReference extends config_http implements Structure.ByReference {
		
	};
	public static class ByValue extends config_http implements Structure.ByValue {
		
	};
}
