package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : config_gw.h:151</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class config_size extends Structure {
	public short width;
	public short height;
	public config_size() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("width", "height");
	}
	public config_size(short width, short height) {
		super();
		this.width = width;
		this.height = height;
	}
	public static class ByReference extends config_size implements Structure.ByReference {
		
	};
	public static class ByValue extends config_size implements Structure.ByValue {
		
	};
}
