package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u8f66\u4f4d\u76f8\u673a\u6574\u4f53\u914d\u7f6e\u4fe1\u606f<br>
 * <i>native declaration : config_gw.h:554</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class config_gw_car_port extends Structure {
	/** \u63a7\u706f\u6a21\u5f0f  1\u5185\u7f6e\u706f 2 \u5916\u7f6e\u706f 3 \u5185\u52a0\u5916 */
	public int lightControlMode;
	/**
	 * \u4ea4\u66ff\u63a7\u706f<br>
	 * C type : config_carbinet_inturn_control
	 */
	public config_carbinet_inturn_control inturnControl;
	/**
	 * \u8f66\u4f4d\u72b6\u6001\u914d\u7f6e<br>
	 * C type : config_carbinet_state[(8)]
	 */
	public config_carbinet_state[] carbinetState = new config_carbinet_state[8];
	/**
	 * \u8f66\u4f4d\u914d\u7f6e\u4fe1\u606f<br>
	 * C type : config_carbinet[(4)]
	 */
	public config_carbinet[] carbinet = new config_carbinet[4];
	/**
	 * \u8f66\u4f4d\u76f8\u673a\u7b97\u6cd5\u914d\u7f6e<br>
	 * C type : config_carbinet_vdetect
	 */
	public config_carbinet_vdetect alg;
	public config_gw_car_port() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("lightControlMode", "inturnControl", "carbinetState", "carbinet", "alg");
	}
	/**
	 * @param lightControlMode \u63a7\u706f\u6a21\u5f0f  1\u5185\u7f6e\u706f 2 \u5916\u7f6e\u706f 3 \u5185\u52a0\u5916<br>
	 * @param inturnControl \u4ea4\u66ff\u63a7\u706f<br>
	 * C type : config_carbinet_inturn_control<br>
	 * @param carbinetState \u8f66\u4f4d\u72b6\u6001\u914d\u7f6e<br>
	 * C type : config_carbinet_state[(8)]<br>
	 * @param carbinet \u8f66\u4f4d\u914d\u7f6e\u4fe1\u606f<br>
	 * C type : config_carbinet[(4)]<br>
	 * @param alg \u8f66\u4f4d\u76f8\u673a\u7b97\u6cd5\u914d\u7f6e<br>
	 * C type : config_carbinet_vdetect
	 */
	public config_gw_car_port(int lightControlMode, config_carbinet_inturn_control inturnControl, config_carbinet_state carbinetState[], config_carbinet carbinet[], config_carbinet_vdetect alg) {
		super();
		this.lightControlMode = lightControlMode;
		this.inturnControl = inturnControl;
		if ((carbinetState.length != this.carbinetState.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.carbinetState = carbinetState;
		if ((carbinet.length != this.carbinet.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.carbinet = carbinet;
		this.alg = alg;
	}
	public static class ByReference extends config_gw_car_port implements Structure.ByReference {
		
	};
	public static class ByValue extends config_gw_car_port implements Structure.ByValue {
		
	};
}
