package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u4eba\u8138\u68c0\u6d4b\u53c2\u6570\u7684\u914d\u7f6e\u3001\u6821\u9a8c\u3001\u91cd\u7f6e *****<br>
 * <i>native declaration : config_gw.h:315</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class config_face_detect extends Structure {
	public int enable;
	/** \u662f\u5426\u53d1\u9001\u8c03\u8bd5\u56fe\u50cf\u7b49 */
	public int debug;
	/**
	 * \u4ece\u539f\u56fe\u4e0a\u53d6\u4e00\u90e8\u5206\u8fdb\u884c\u68c0\u6d4b<br>
	 * C type : config_rect
	 */
	public config_rect detect_area;
	/**
	 * \u6307\u5b9a\u68c0\u6d4b\u56fe\u4e0a\u4eba\u8138\u6240\u5360\u50cf\u7d20\u8303\u56f4<br>
	 * C type : config_size
	 */
	public config_size minsize;
	/** C type : config_size */
	public config_size maxsize;
	/** \u6bcf\u6b21\u68c0\u6d4b\u6b65\u8fdb\u6bd4\u4f8b */
	public float step;
	/** \u4ece\u539f\u6765\u9884\u7559\u768464\u5b57\u8282\u4e2d\u53d6\u51fa\u4e00\u70b9 */
	public float ratio;
	/** \u8df3\u5e27\u6570 */
	public int interval;
	/** \u4f7f\u7528\u8fd0\u52a8\u68c0\u6d4b\u8fdb\u884c\u6293\u62cd */
	public int use_motion;
	/** \u5728\u8fd0\u52a8\u68c0\u6d4b\u7684\u57fa\u7840\u4e0a,\u9694\u591a\u5c11\u6b21\u68c0\u6d4b\u4e00\u6b21\u4eba\u8138 */
	public int face_step;
	/**
	 * \u9884\u7559<br>
	 * C type : char[48]
	 */
	public byte[] resv = new byte[48];
	public config_face_detect() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enable", "debug", "detect_area", "minsize", "maxsize", "step", "ratio", "interval", "use_motion", "face_step", "resv");
	}
	public static class ByReference extends config_face_detect implements Structure.ByReference {
		
	};
	public static class ByValue extends config_face_detect implements Structure.ByValue {
		
	};
}
