package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : config_gw.h:475</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class config_gw_park extends Structure {
	/** 1\u4e3a\u79bb\u7ebf\uff0c0\u4e3a\u5728\u7ebf, 2\u4e3a\u81ea\u52a8\uff08\u5373\u8131\u673a\u68c0\u67e5\uff09 */
	public byte offline;
	/** 0\u4e3a\u767d\u540d\u5355\u5f00\uff0c1\u4e3a\u8fc7\u8f66\u5f00 */
	public byte alarm_out_mode;
	/** \u4e0a\u4f20\u79bb\u7ebf\u6570\u636e */
	public byte transfer_offline_data;
	/** \u4e2d\u65ad/\u6062\u590d\u539f\u672c\u8bbe\u5907\u63a7\u5236\u7684\u4e32\u53e3\u8f93\u51fa\uff0c\u900f\u660e\u4e32\u53e3\u8f93\u51fa\u4e0d\u5728\u6b64\u63a7\u5236 */
	public byte diable_serial_output;
	/** \u6a21\u7cca\u5339\u914d\u8f66\u724c\u9600\u503c */
	public byte same_count;
	/** \u6700\u5c0f\u97f3\u91cf */
	public byte min_volume;
	/** \u6700\u5927\u97f3\u91cf */
	public byte max_volume;
	/** \u5f53\u524d\u97f3\u91cf */
	public byte cur_volume;
	public byte light;
	/** 0:\u5168\u6293, 1:\u53ea\u6293\u8f66\u5934\uff0c2\u53ea\u6293\u8f66\u5c3e */
	public byte drive_direct;
	/** 0\u5e38\u4eae\uff0c1\u667a\u80fd\u63a7\u706f\u4f7f\u80fd\uff0c2\u5e38\u95ed\uff0c3\u7ebf\u5708\u95ea\u5149\u6a21\u5f0f */
	public byte ctrl_light_mode;
	/** \u767d\u5929\u4eae\u5ea6\u9600\u503c */
	public byte day_brightness;
	/** \u81ea\u52a8\u5f00\u95f8\u65f6\u95f4\u95f4\u9694(500-5000ms) */
	public short alarmOutDuration;
	/** \u4e2d\u65adGPIO\u63a7\u5236 */
	public byte disable_io_port;
	/** \u4e2d\u65ad/\u6062\u590d\u539f\u672c\u8bbe\u5907\u63a7\u5236\u7684\u7ee7\u7535\u5668\u3001\u7535\u5e73\u8f93\u51fa */
	public byte disable_io_output;
	/** GPIO IN\u4f7f\u80fd\uff0cbit[7-0]\u5bf9\u5e94gpio[7-0] */
	public byte gpio_in;
	/** GPIO OUT\u4f7f\u80fd\uff0cbit[7-0]\u5bf9\u5e94gpio[7-0] */
	public byte gpio_out;
	/** \u540c\u6b65\u8f93\u51faout2 */
	public byte flash_sync_out1;
	/** 0-\u6bcf\u5929\u81ea\u52a8\u91cd\u542f\uff0c1-\u91cd\u4e0d\u91cd\u542f */
	public byte reboot_flag;
	/**
	 * \u5907\u7528<br>
	 * C type : unsigned char[16]
	 */
	public byte[] resv = new byte[16];
	public config_gw_park() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("offline", "alarm_out_mode", "transfer_offline_data", "diable_serial_output", "same_count", "min_volume", "max_volume", "cur_volume", "light", "drive_direct", "ctrl_light_mode", "day_brightness", "alarmOutDuration", "disable_io_port", "disable_io_output", "gpio_in", "gpio_out", "flash_sync_out1", "reboot_flag", "resv");
	}
	public static class ByReference extends config_gw_park implements Structure.ByReference {
		
	};
	public static class ByValue extends config_gw_park implements Structure.ByValue {
		
	};
}
