package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : FaceRecoDef.h:214</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DebugImageInfo extends Structure {
	/** \u65f6\u95f4\u6233 \u79d2 */
	public int timeStamp_s;
	/** \u65f6\u95f4\u6233 \u5fae\u5999 */
	public int timeStamp_u;
	/** \u6bd4\u5bf9\u7ed3\u679c\uff0c0\uff1a\u672a\u6bd4\u5bf9\u3002-1\uff1a\u6bd4\u5bf9\u5931\u8d25\u30021\uff1a\u6bd4\u5bf9\u6210\u529f */
	public int matched;
	/** \u6bd4\u5bf9\u5206\u6570 */
	public int matchScore;
	/**
	 * \u6bd4\u5bf9\u4e0a\u7684\u4eba\u5458id\uff0cmatched\u7b49\u4e8e1\u65f6\u6709\u6548<br>
	 * C type : char[20]
	 */
	public byte[] faceId = new byte[20];
	/** \u8c03\u8bd5\u56fe\u50cf\u6570\u91cf\uff0c\u6700\u5927\u652f\u63016\u5f20\u56fe\u50cf */
	public int imageNum;
	/**
	 * \u8c03\u8bd5\u56fe\u50cf\u4fe1\u606f<br>
	 * C type : DebugImage[6]
	 */
	public DebugImage[] debugImage = new DebugImage[6];
	public DebugImageInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("timeStamp_s", "timeStamp_u", "matched", "matchScore", "faceId", "imageNum", "debugImage");
	}
	/**
	 * @param timeStamp_s \u65f6\u95f4\u6233 \u79d2<br>
	 * @param timeStamp_u \u65f6\u95f4\u6233 \u5fae\u5999<br>
	 * @param matched \u6bd4\u5bf9\u7ed3\u679c\uff0c0\uff1a\u672a\u6bd4\u5bf9\u3002-1\uff1a\u6bd4\u5bf9\u5931\u8d25\u30021\uff1a\u6bd4\u5bf9\u6210\u529f<br>
	 * @param matchScore \u6bd4\u5bf9\u5206\u6570<br>
	 * @param faceId \u6bd4\u5bf9\u4e0a\u7684\u4eba\u5458id\uff0cmatched\u7b49\u4e8e1\u65f6\u6709\u6548<br>
	 * C type : char[20]<br>
	 * @param imageNum \u8c03\u8bd5\u56fe\u50cf\u6570\u91cf\uff0c\u6700\u5927\u652f\u63016\u5f20\u56fe\u50cf<br>
	 * @param debugImage \u8c03\u8bd5\u56fe\u50cf\u4fe1\u606f<br>
	 * C type : DebugImage[6]
	 */
	public DebugImageInfo(int timeStamp_s, int timeStamp_u, int matched, int matchScore, byte faceId[], int imageNum, DebugImage debugImage[]) {
		super();
		this.timeStamp_s = timeStamp_s;
		this.timeStamp_u = timeStamp_u;
		this.matched = matched;
		this.matchScore = matchScore;
		if ((faceId.length != this.faceId.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.faceId = faceId;
		this.imageNum = imageNum;
		if ((debugImage.length != this.debugImage.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.debugImage = debugImage;
	}
	public static class ByReference extends DebugImageInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends DebugImageInfo implements Structure.ByValue {
		
	};
}
