package sdk.facecamera.sdk.sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : FaceRecoDef.h:205</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DebugImage extends Structure {
	/** \u8c03\u8bd5\u56fe\u50cf\u683c\u5f0f, 1:jpg */
	public int format;
	/** \u8c03\u8bd5\u56fe\u50cf\u5bbd\u5ea6 */
	public short width;
	/** \u8c03\u8bd5\u56fe\u50cf\u9ad8\u5ea6 */
	public short height;
	/** \u56fe\u50cf\u6570\u636e\u957f\u5ea6 */
	public int imageLen;
	/**
	 * \u56fe\u50cf\u6570\u636e<br>
	 * C type : unsigned char*
	 */
	public Pointer imgData;
	public DebugImage() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("format", "width", "height", "imageLen", "imgData");
	}
	/**
	 * @param format \u8c03\u8bd5\u56fe\u50cf\u683c\u5f0f, 1:jpg<br>
	 * @param width \u8c03\u8bd5\u56fe\u50cf\u5bbd\u5ea6<br>
	 * @param height \u8c03\u8bd5\u56fe\u50cf\u9ad8\u5ea6<br>
	 * @param imageLen \u56fe\u50cf\u6570\u636e\u957f\u5ea6<br>
	 * @param imgData \u56fe\u50cf\u6570\u636e<br>
	 * C type : unsigned char*
	 */
	public DebugImage(int format, short width, short height, int imageLen, Pointer imgData) {
		super();
		this.format = format;
		this.width = width;
		this.height = height;
		this.imageLen = imageLen;
		this.imgData = imgData;
	}
	public static class ByReference extends DebugImage implements Structure.ByReference {
		
	};
	public static class ByValue extends DebugImage implements Structure.ByValue {
		
	};
}
