package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : FaceRecoDef.h:92</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ErrorFaceImage extends Structure {
	/** \u6ce8\u518c\u5931\u8d25\u7684\u56fe\u50cf\u7f16\u53f7 */
	public int img_seq;
	/** \u5931\u8d25\u7684\u9519\u8bef\u7801 */
	public int err_code;
	public ErrorFaceImage() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("img_seq", "err_code");
	}
	/**
	 * @param img_seq \u6ce8\u518c\u5931\u8d25\u7684\u56fe\u50cf\u7f16\u53f7<br>
	 * @param err_code \u5931\u8d25\u7684\u9519\u8bef\u7801
	 */
	public ErrorFaceImage(int img_seq, int err_code) {
		super();
		this.img_seq = img_seq;
		this.err_code = err_code;
	}
	public static class ByReference extends ErrorFaceImage implements Structure.ByReference {
		
	};
	public static class ByValue extends ErrorFaceImage implements Structure.ByValue {
		
	};
}
