package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u7a7f\u900f\u5916\u7f51\u914d\u7f6e<br>
 * <i>native declaration : config_gw.h:812</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ExtranetParam extends Structure {
	/**
	 * \u4ee5TCP\u5ba2\u6237\u7aef\u65b9\u5f0f\u76f4\u8fbe\u5916\u7f51\u3002<br>
	 * C type : TcpClientParam
	 */
	public TcpClientParam client;
	/** \u4f7f\u80fd\u5f00\u5173\u3002 */
	public byte enable;
	/**
	 * \u4fdd\u7559\u3002<br>
	 * C type : char[7]
	 */
	public byte[] resv = new byte[7];
	public ExtranetParam() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("client", "enable", "resv");
	}
	/**
	 * @param client \u4ee5TCP\u5ba2\u6237\u7aef\u65b9\u5f0f\u76f4\u8fbe\u5916\u7f51\u3002<br>
	 * C type : TcpClientParam<br>
	 * @param enable \u4f7f\u80fd\u5f00\u5173\u3002<br>
	 * @param resv \u4fdd\u7559\u3002<br>
	 * C type : char[7]
	 */
	public ExtranetParam(TcpClientParam client, byte enable, byte resv[]) {
		super();
		this.client = client;
		this.enable = enable;
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
	}
	public static class ByReference extends ExtranetParam implements Structure.ByReference {
		
	};
	public static class ByValue extends ExtranetParam implements Structure.ByValue {
		
	};
}
