package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : FaceRecoDef.h:197</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FaceReRegistProgressInfo extends Structure {
	/** \u91cd\u6ce8\u518c\u7684\u4eba\u5458\u603b\u6570 */
	public int regist_count;
	/** \u5f53\u524d\u91cd\u6ce8\u518c\u7b2c\u51e0\u6761\u7eaa\u5f55 */
	public int cur_regist_no;
	/**
	 * \u5f53\u524d\u91cd\u6ce8\u518c\u7684\u4eba\u5458id<br>
	 * C type : char[20]
	 */
	public byte[] faceId = new byte[20];
	public FaceReRegistProgressInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("regist_count", "cur_regist_no", "faceId");
	}
	/**
	 * @param regist_count \u91cd\u6ce8\u518c\u7684\u4eba\u5458\u603b\u6570<br>
	 * @param cur_regist_no \u5f53\u524d\u91cd\u6ce8\u518c\u7b2c\u51e0\u6761\u7eaa\u5f55<br>
	 * @param faceId \u5f53\u524d\u91cd\u6ce8\u518c\u7684\u4eba\u5458id<br>
	 * C type : char[20]
	 */
	public FaceReRegistProgressInfo(int regist_count, int cur_regist_no, byte faceId[]) {
		super();
		this.regist_count = regist_count;
		this.cur_regist_no = cur_regist_no;
		if ((faceId.length != this.faceId.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.faceId = faceId;
	}
	public static class ByReference extends FaceReRegistProgressInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends FaceReRegistProgressInfo implements Structure.ByValue {
		
	};
}
