package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : FaceRecoDef.h:190</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FaceDelProgressInfo extends Structure {
	/** \u5220\u9664\u7684\u7eaa\u5f55\u603b\u6570 */
	public int delCount;
	/** \u5f53\u524d\u5220\u9664\u7b2c\u51e0\u6761\u7eaa\u5f55 */
	public int curDelNo;
	/**
	 * \u5f53\u524d\u5220\u9664\u7684\u4eba\u5458ID<br>
	 * C type : char[20]
	 */
	public byte[] faceId = new byte[20];
	public FaceDelProgressInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("delCount", "curDelNo", "faceId");
	}
	/**
	 * @param delCount \u5220\u9664\u7684\u7eaa\u5f55\u603b\u6570<br>
	 * @param curDelNo \u5f53\u524d\u5220\u9664\u7b2c\u51e0\u6761\u7eaa\u5f55<br>
	 * @param faceId \u5f53\u524d\u5220\u9664\u7684\u4eba\u5458ID<br>
	 * C type : char[20]
	 */
	public FaceDelProgressInfo(int delCount, int curDelNo, byte faceId[]) {
		super();
		this.delCount = delCount;
		this.curDelNo = curDelNo;
		if ((faceId.length != this.faceId.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.faceId = faceId;
	}
	public static class ByReference extends FaceDelProgressInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends FaceDelProgressInfo implements Structure.ByValue {
		
	};
}
