package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : FaceRecoDef.h:71</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FaceFlags extends Structure {
	/**
	 * \u4eba\u5458ID<br>
	 * C type : char[20]
	 */
	public byte[] faceID = new byte[20];
	/**
	 * \u4eba\u5458\u59d3\u540d<br>
	 * C type : char[16]
	 */
	public byte[] faceName = new byte[16];
	/** \u4eba\u5458\u89d2\u8272\uff0c0\uff1a\u666e\u901a\u4eba\u5458\u3002 1\uff1a\u767d\u540d\u5355\u4eba\u5458\u3002 2\uff1a\u9ed1\u540d\u5355\u4eba\u5458\u3002 -1\uff1a\u6240\u6709\u4eba\u5458\u3002 */
	public int role;
	/** \u97e6\u6839\u534f\u8bae\u95e8\u7981\u5361\u53f7 */
	public int wgCardNO;
	/** \u6709\u6548\u671f\u622a\u6b62\u65f6\u95f4\uff0c\u8be5\u4eba\u5458\u4fe1\u606f\u5728\u8be5\u65f6\u95f4\u5185\u6709\u6548,\u4ece1970\u5e741\u67081\u65e50\u65f60\u52060\u79d2\u5230\u622a\u6b62\u65f6\u95f4\u7684\u79d2\u6570\uff080xFFFFFFFF\u8868\u793a\u6c38\u4e45\u6709\u6548\uff0c0\u8868\u793a\u6c38\u4e45\u5931\u6548\uff09 */
	public int effectTime;
	/** \u6709\u6548\u671f\u8d77\u59cb\u65f6\u95f4\uff0c\u8be5\u4eba\u5458\u4fe1\u606f\u5728\u8be5\u65f6\u95f4\u4e4b\u540e\u6709\u6548,\u4ece1970\u5e741\u67081\u65e50\u65f60\u52060\u79d2\u5230\u8d77\u59cb\u65f6\u95f4\u7684\u79d2\u6570\uff080\u8868\u793a\u672a\u521d\u59cb\u5316\uff09 */
	public int effectStartTime;
	/** C type : char[8184] */
	public byte[] resv = new byte[8184];
	public FaceFlags() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("faceID", "faceName", "role", "wgCardNO", "effectTime", "effectStartTime", "resv");
	}
	/**
	 * @param faceID \u4eba\u5458ID<br>
	 * C type : char[20]<br>
	 * @param faceName \u4eba\u5458\u59d3\u540d<br>
	 * C type : char[16]<br>
	 * @param role \u4eba\u5458\u89d2\u8272\uff0c0\uff1a\u666e\u901a\u4eba\u5458\u3002 1\uff1a\u767d\u540d\u5355\u4eba\u5458\u3002 2\uff1a\u9ed1\u540d\u5355\u4eba\u5458\u3002 -1\uff1a\u6240\u6709\u4eba\u5458\u3002<br>
	 * @param wgCardNO \u97e6\u6839\u534f\u8bae\u95e8\u7981\u5361\u53f7<br>
	 * @param effectTime \u6709\u6548\u671f\u622a\u6b62\u65f6\u95f4\uff0c\u8be5\u4eba\u5458\u4fe1\u606f\u5728\u8be5\u65f6\u95f4\u5185\u6709\u6548,\u4ece1970\u5e741\u67081\u65e50\u65f60\u52060\u79d2\u5230\u622a\u6b62\u65f6\u95f4\u7684\u79d2\u6570\uff080xFFFFFFFF\u8868\u793a\u6c38\u4e45\u6709\u6548\uff0c0\u8868\u793a\u6c38\u4e45\u5931\u6548\uff09<br>
	 * @param effectStartTime \u6709\u6548\u671f\u8d77\u59cb\u65f6\u95f4\uff0c\u8be5\u4eba\u5458\u4fe1\u606f\u5728\u8be5\u65f6\u95f4\u4e4b\u540e\u6709\u6548,\u4ece1970\u5e741\u67081\u65e50\u65f60\u52060\u79d2\u5230\u8d77\u59cb\u65f6\u95f4\u7684\u79d2\u6570\uff080\u8868\u793a\u672a\u521d\u59cb\u5316\uff09<br>
	 * @param resv C type : char[8184]
	 */
	public FaceFlags(byte faceID[], byte faceName[], int role, int wgCardNO, int effectTime, int effectStartTime, byte resv[]) {
		super();
		if ((faceID.length != this.faceID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.faceID = faceID;
		if ((faceName.length != this.faceName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.faceName = faceName;
		this.role = role;
		this.wgCardNO = wgCardNO;
		this.effectTime = effectTime;
		this.effectStartTime = effectStartTime;
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
	}
	public static class ByReference extends FaceFlags implements Structure.ByReference {
		
	};
	public static class ByValue extends FaceFlags implements Structure.ByValue {
		
	};
}
