package sdk.facecamera.sdk.sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : FaceRecoDef.h:82</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FaceImage extends Structure {
	/** \u56fe\u7247\u7f16\u53f7 */
	public int img_seq;
	/** \u56fe\u7247\u683c\u5f0f 0\uff1ajpg 1\uff1abgr */
	public int img_fmt;
	/**
	 * \u8981\u6ce8\u518c\u7684\u4eba\u8138\u56fe\u7247\u6570\u636e\uff0c\u652f\u6301\u4e3b\u6d41\u56fe\u50cf\u683c\u5f0f<br>
	 * C type : unsigned char*
	 */
	public Pointer img;
	/** img\u7684\u957f\u5ea6 */
	public int img_len;
	/** \u56fe\u50cf\u5bbd\u5ea6\uff0cjpg\u56fe\u50cf\u4e0d\u586b\u6b64\u9879 */
	public int width;
	/** \u56fe\u50cf\u9ad8\u5ea6\uff0cjpg\u56fe\u50cf\u4e0d\u586b\u6b64\u9879 */
	public int height;
	public FaceImage() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("img_seq", "img_fmt", "img", "img_len", "width", "height");
	}
	/**
	 * @param img_seq \u56fe\u7247\u7f16\u53f7<br>
	 * @param img_fmt \u56fe\u7247\u683c\u5f0f 0\uff1ajpg 1\uff1abgr<br>
	 * @param img \u8981\u6ce8\u518c\u7684\u4eba\u8138\u56fe\u7247\u6570\u636e\uff0c\u652f\u6301\u4e3b\u6d41\u56fe\u50cf\u683c\u5f0f<br>
	 * C type : unsigned char*<br>
	 * @param img_len img\u7684\u957f\u5ea6<br>
	 * @param width \u56fe\u50cf\u5bbd\u5ea6\uff0cjpg\u56fe\u50cf\u4e0d\u586b\u6b64\u9879<br>
	 * @param height \u56fe\u50cf\u9ad8\u5ea6\uff0cjpg\u56fe\u50cf\u4e0d\u586b\u6b64\u9879
	 */
	public FaceImage(int img_seq, int img_fmt, Pointer img, int img_len, int width, int height) {
		super();
		this.img_seq = img_seq;
		this.img_fmt = img_fmt;
		this.img = img;
		this.img_len = img_len;
		this.width = width;
		this.height = height;
	}
	public static class ByReference extends FaceImage implements Structure.ByReference {
		
	};
	public static class ByValue extends FaceImage implements Structure.ByValue {
		
	};
}
