package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u5b50\u7cfb\u7edf\u53c2\u6570\u3002<br>
 * <i>native declaration : config_gw.h:969</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FaceSystemConfig extends Structure {
	/**
	 * ------28\u5b57\u8282<br>
	 * C type : TemporaryParam
	 */
	public TemporaryParam temp;
	/**
	 * ---640\u5b57\u8282<br>
	 * C type : PlatformParam
	 */
	public PlatformParam platform;
	/**
	 * ---64\u5b57\u8282<br>
	 * C type : StreamParam
	 */
	public StreamParam stream;
	/**
	 * -------------1024\u5b57\u8282<br>
	 * C type : AppParam
	 */
	public AppParam app;
	/**
	 * ---128\u5b57\u8282<br>
	 * C type : OutputerParam
	 */
	public OutputerParam outputer;
	public FaceSystemConfig() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("temp", "platform", "stream", "app", "outputer");
	}
	/**
	 * @param temp ------28\u5b57\u8282<br>
	 * C type : TemporaryParam<br>
	 * @param platform ---640\u5b57\u8282<br>
	 * C type : PlatformParam<br>
	 * @param stream ---64\u5b57\u8282<br>
	 * C type : StreamParam<br>
	 * @param app -------------1024\u5b57\u8282<br>
	 * C type : AppParam<br>
	 * @param outputer ---128\u5b57\u8282<br>
	 * C type : OutputerParam
	 */
	public FaceSystemConfig(TemporaryParam temp, PlatformParam platform, StreamParam stream, AppParam app, OutputerParam outputer) {
		super();
		this.temp = temp;
		this.platform = platform;
		this.stream = stream;
		this.app = app;
		this.outputer = outputer;
	}
	public static class ByReference extends FaceSystemConfig implements Structure.ByReference {
		
	};
	public static class ByValue extends FaceSystemConfig implements Structure.ByValue {
		
	};
}
