package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : config_gw.h:1114</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FtpInfo extends Structure {
	/**
	 * \u7528\u6237\u540d<br>
	 * C type : char[15]
	 */
	public byte[] user_name = new byte[15];
	/**
	 * \u5bc6\u7801<br>
	 * C type : char[15]
	 */
	public byte[] passwd = new byte[15];
	/**
	 * \u8def\u5f84<br>
	 * C type : char[70]
	 */
	public byte[] path = new byte[70];
	/**
	 * \u7a7a\u95f2<br>
	 * C type : char[2]
	 */
	public byte[] resv = new byte[2];
	public FtpInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("user_name", "passwd", "path", "resv");
	}
	/**
	 * @param user_name \u7528\u6237\u540d<br>
	 * C type : char[15]<br>
	 * @param passwd \u5bc6\u7801<br>
	 * C type : char[15]<br>
	 * @param path \u8def\u5f84<br>
	 * C type : char[70]<br>
	 * @param resv \u7a7a\u95f2<br>
	 * C type : char[2]
	 */
	public FtpInfo(byte user_name[], byte passwd[], byte path[], byte resv[]) {
		super();
		if ((user_name.length != this.user_name.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.user_name = user_name;
		if ((passwd.length != this.passwd.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.passwd = passwd;
		if ((path.length != this.path.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.path = path;
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
	}
	public static class ByReference extends FtpInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends FtpInfo implements Structure.ByValue {
		
	};
}
