package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : HASdkDef.h:207</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class HA_AllowList extends Structure {
	/**
	 * \u8f66\u724c\u53f7<br>
	 * C type : char[16]
	 */
	public byte[] plate = new byte[16];
	/** \u8f66\u724c\u989c\u8272 */
	public short plateColor;
	/** \u8bb0\u5f55\u7684\u8fc7\u671f\u65f6\u95f4-\u5e74 */
	public short year;
	/** \u6708 */
	public short month;
	/** \u65e5 */
	public short day;
	/** \u65f6 */
	public byte hour;
	/** \u5206 */
	public byte min;
	/** \u79d2 */
	public byte sec;
	/** \u8bb0\u5f55\u662f\u5426\u6709\u6548\u6807\u5fd7 */
	public byte bEnable;
	/** \u8bb0\u5f55\u7684\u751f\u6548\u65f6\u95f4-\u5e74 */
	public short enable_year;
	/** \u6708 */
	public byte enable_month;
	/** \u65e5 */
	public byte enable_day;
	/** \u65f6 */
	public byte enable_hour;
	/** \u5206 */
	public byte enable_min;
	/** \u79d2 */
	public byte enable_sec;
	/** \u662f\u5426\u89e6\u53d1\u62a5\u8b66\uff08\u9ed1\u540d\u5355\u8bb0\u5f55\uff09 */
	public byte bAlarm;
	/** C type : int[13] */
	public int[] resv = new int[13];
	public HA_AllowList() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("plate", "plateColor", "year", "month", "day", "hour", "min", "sec", "bEnable", "enable_year", "enable_month", "enable_day", "enable_hour", "enable_min", "enable_sec", "bAlarm", "resv");
	}
	public static class ByReference extends HA_AllowList implements Structure.ByReference {
		
	};
	public static class ByValue extends HA_AllowList implements Structure.ByValue {
		
	};
}
