package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : FaceRecoDef.h:166</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ha_rect extends Structure {
	/** \u4eba\u8138\u77e9\u5f62\u533a\u57df\u5de6\u4e0a\u89d2x\u5750\u6807 */
	public short x;
	/** \u4eba\u8138\u77e9\u5f62\u533a\u57df\u5de6\u4e0a\u89d2y\u5750\u6807 */
	public short y;
	/** \u4eba\u8138\u77e9\u5f62\u533a\u57df\u5bbd\u5ea6 */
	public short width;
	/** \u4eba\u8138\u77e9\u5f62\u533a\u57df\u9ad8\u5ea6 */
	public short height;
	public ha_rect() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("x", "y", "width", "height");
	}
	/**
	 * @param x \u4eba\u8138\u77e9\u5f62\u533a\u57df\u5de6\u4e0a\u89d2x\u5750\u6807<br>
	 * @param y \u4eba\u8138\u77e9\u5f62\u533a\u57df\u5de6\u4e0a\u89d2y\u5750\u6807<br>
	 * @param width \u4eba\u8138\u77e9\u5f62\u533a\u57df\u5bbd\u5ea6<br>
	 * @param height \u4eba\u8138\u77e9\u5f62\u533a\u57df\u9ad8\u5ea6
	 */
	public ha_rect(short x, short y, short width, short height) {
		super();
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = height;
	}
	public static class ByReference extends ha_rect implements Structure.ByReference {
		
	};
	public static class ByValue extends ha_rect implements Structure.ByValue {
		
	};
}
