package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : config_gw.h:450</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class lamp_area extends Structure {
	/** 2\u706for3\u706f */
	public int lamp_num;
	public short only_red_x;
	public short only_red_y;
	public short only_red_w;
	public short only_red_h;
	public short all_lamp_x;
	public short all_lamp_y;
	public short all_lamp_w;
	public short all_lamp_h;
	public lamp_area() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("lamp_num", "only_red_x", "only_red_y", "only_red_w", "only_red_h", "all_lamp_x", "all_lamp_y", "all_lamp_w", "all_lamp_h");
	}
	/** @param lamp_num 2\u706for3\u706f */
	public lamp_area(int lamp_num, short only_red_x, short only_red_y, short only_red_w, short only_red_h, short all_lamp_x, short all_lamp_y, short all_lamp_w, short all_lamp_h) {
		super();
		this.lamp_num = lamp_num;
		this.only_red_x = only_red_x;
		this.only_red_y = only_red_y;
		this.only_red_w = only_red_w;
		this.only_red_h = only_red_h;
		this.all_lamp_x = all_lamp_x;
		this.all_lamp_y = all_lamp_y;
		this.all_lamp_w = all_lamp_w;
		this.all_lamp_h = all_lamp_h;
	}
	public static class ByReference extends lamp_area implements Structure.ByReference {
		
	};
	public static class ByValue extends lamp_area implements Structure.ByValue {
		
	};
}
