package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * NTP\u6821\u65f6\u4fe1\u606f<br>
 * <i>native declaration : FaceRecoDef.h:131</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NtpInfo extends Structure {
	/** Ntp\u5f00\u5173\u72b6\u6001\uff0c0\u662f\u5173 \u975e0\u662f\u5f00 */
	public short enable_state;
	/** \u66f4\u65b0\u5468\u671f\uff0c60~600s */
	public short update_cycle;
	/**
	 * NTP\u670d\u52a1\u5668ip\u5730\u5740<br>
	 * C type : char[16]
	 */
	public byte[] ntp_server = new byte[16];
	/**
	 * \u4fdd\u7559<br>
	 * C type : char[12]
	 */
	public byte[] resv = new byte[12];
	public NtpInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enable_state", "update_cycle", "ntp_server", "resv");
	}
	/**
	 * @param enable_state Ntp\u5f00\u5173\u72b6\u6001\uff0c0\u662f\u5173 \u975e0\u662f\u5f00<br>
	 * @param update_cycle \u66f4\u65b0\u5468\u671f\uff0c60~600s<br>
	 * @param ntp_server NTP\u670d\u52a1\u5668ip\u5730\u5740<br>
	 * C type : char[16]<br>
	 * @param resv \u4fdd\u7559<br>
	 * C type : char[12]
	 */
	public NtpInfo(short enable_state, short update_cycle, byte ntp_server[], byte resv[]) {
		super();
		this.enable_state = enable_state;
		this.update_cycle = update_cycle;
		if ((ntp_server.length != this.ntp_server.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ntp_server = ntp_server;
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
	}
	public static class ByReference extends NtpInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends NtpInfo implements Structure.ByValue {
		
	};
}
