package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u8f93\u51fa\u53c2\u6570\u3002\u5927\u5c0f\u5e94\u56fa\u5b9a\u4e3a128\u5b57\u8282\u3002<br>
 * <i>native declaration : config_gw.h:962</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class OutputerParam extends Structure {
	/** C type : UploaderParam */
	public UploaderParam uploader;
	public OutputerParam() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("uploader");
	}
	/** @param uploader C type : UploaderParam */
	public OutputerParam(UploaderParam uploader) {
		super();
		this.uploader = uploader;
	}
	public static class ByReference extends OutputerParam implements Structure.ByReference {
		
	};
	public static class ByValue extends OutputerParam implements Structure.ByValue {
		
	};
}
