package sdk.facecamera.sdk.sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * @brief   \u8f66\u8f86\u4fe1\u606f\u5305<br>
 * <i>native declaration : pkg_vehicle.h:13</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class pkg_vehicle extends Structure {
	/** \u5305\u5e8f\u53f7, \u9012\u589e */
	public int sequence_id;
	/** - */
	public int realtime_data;
	/**
	 * - \u5305ID<br>
	 * C type : char[64]
	 */
	public byte[] packet_id = new byte[64];
	/**
	 * \u8bbe\u5907\u7f16\u53f7<br>
	 * C type : char[32]
	 */
	public byte[] device_id = new byte[32];
	/**
	 * \u5730\u70b9\u7f16\u53f7<br>
	 * C type : char[32]
	 */
	public byte[] addr_id = new byte[32];
	/**
	 * \u65b9\u5411\u7f16\u53f7<br>
	 * C type : char[32]
	 */
	public byte[] direction_id = new byte[32];
	/**
	 * \u76f8\u673a\u7f16\u53f7<br>
	 * C type : char[32]
	 */
	public byte[] camera_id = new byte[32];
	/**
	 * \u8f66\u9053\u7f16\u53f7<br>
	 * C type : char[32]
	 */
	public byte[] lane_id = new byte[32];
	/**
	 * \u5730\u70b9\u540d\u79f0<br>
	 * C type : char[96]
	 */
	public byte[] addr_name = new byte[96];
	/**
	 * \u65b9\u5411\u540d\u79f0<br>
	 * C type : char[96]
	 */
	public byte[] direction_name = new byte[96];
	/**
	 * \u8f66\u724c, \u8f66\u724c\u5750\u6807, \u8f66\u724c\u7f6e\u4fe1\u5ea6<br>
	 * \u8f66\u724c\u53f7\u7801, utf8\u7f16\u7801<br>
	 * C type : char[16]
	 */
	public byte[] plate = new byte[16];
	/** \u8f66\u724c\u5728\u753b\u9762\u4e2d\u7684\u5de6\u4e0a\u89d2x\u5750\u6807 */
	public short plate_x;
	/** \u8f66\u724c\u5728\u753b\u9762\u4e2d\u7684\u5de6\u4e0a\u89d2y\u5750\u6807 */
	public short plate_y;
	/** \u8f66\u724c\u5728\u753b\u9762\u4e2d\u7684\u50cf\u7d20\u5bbd\u5ea6 */
	public short plate_w;
	/** \u8f66\u724c\u5728\u753b\u9762\u4e2d\u7684\u50cf\u7d20\u9ad8\u5ea6 */
	public short plate_h;
	/** - \u7f6e\u4fe1\u5ea6 */
	public int plate_confidence;
	/** \u8f66\u724c\u989c\u8272 // 0-\u84dd\u8272 1-\u9ed1\u8272 2-\u9ec4\u8272 3-\u767d\u8272 4-\u7eff\u8272 5-\u7ea2\u8272 6-\u7070\u8272 7-\u7d2b\u8272(KISE) */
	public byte plate_color;
	/** - \u8f66\u8f86\u7c7b\u578b */
	public byte vehicle_style;
	/** - \u8f66\u8eab\u989c\u8272 */
	public byte vehicle_color;
	/** - \u89e6\u53d1\u7c7b\u578b */
	public byte triger_type;
	public int redlight_begin_sec;
	public int redlight_begin_usec;
	public int system_type;
	public int vio_type;
	public short vehicle_speed;
	public short limit_speed;
	public int recoImageIndex;
	/** C type : unsigned short[4] */
	public short[] vehicle_x = new short[4];
	/** C type : unsigned short[4] */
	public short[] vehicle_y = new short[4];
	/** C type : unsigned short[4] */
	public short[] vehicle_w = new short[4];
	/** C type : unsigned short[4] */
	public short[] vehicle_h = new short[4];
	/**
	 * 4\u65b9\u5411\u706f\u533a\u57df<br>
	 * C type : unsigned short[4]
	 */
	public short[] red_lamp_x = new short[4];
	/** C type : unsigned short[4] */
	public short[] red_lamp_y = new short[4];
	/** C type : unsigned short[4] */
	public short[] red_lamp_w = new short[4];
	/** C type : unsigned short[4] */
	public short[] red_lamp_h = new short[4];
	/** \u5927\u4e8e\u7b49\u4e8e0\u65f6\u4e3a\u5f53\u524d\u95ef\u7ea2\u706f\u5bf9\u5e94\u706f\u7d22\u5f15 */
	public short vio_red_lamp_index;
	/** \u8f66\u8f86\u884c\u9a76\u65b9\u5411 */
	public short direction;
	/** C type : char[56] */
	public byte[] reserved = new byte[56];
	/** \u672c\u6b21\u643a\u5e26\u7684\u56fe\u7247\u6570\u76ee */
	public byte img_num;
	/** \u672c\u6b21\u643a\u5e26\u7684\u89c6\u9891\u7247\u6bb5\u6570\u76ee */
	public byte video_num;
	/** \u672c\u6b21\u643a\u5e26\u7684\u8f66\u724c\u56fe\u7247\u6570\u76ee */
	public byte plate_img_num;
	/** \u672c\u6b21\u643a\u5e26\u7684\u4eba\u8138\u56fe\u7247\u6570\u76ee */
	public byte face_num;
	/**
	 * \u5bf9\u5e94\u6bcf\u5f20\u56fe\u7247\u7684\u957f\u5ea6<br>
	 * C type : unsigned int[4]
	 */
	public int[] img_len = new int[4];
	/**
	 * \u5bf9\u5e94\u6bcf\u6bb5\u89c6\u9891\u6570\u636e\u7684\u957f\u5ea6<br>
	 * C type : unsigned int[2]
	 */
	public int[] video_len = new int[2];
	/**
	 * \u5bf9\u5e94\u6bcf\u5f20\u8f66\u724c\u56fe\u7247\u7684\u957f\u5ea6<br>
	 * C type : unsigned int[2]
	 */
	public int[] plate_img_len = new int[2];
	/**
	 * \u5bf9\u5e94\u6bcf\u5f20\u4eba\u8138\u56fe\u7247\u7684\u957f\u5ea6<br>
	 * C type : unsigned int[32]
	 */
	public int[] face_img_len = new int[32];
	/**
	 * \u56fe\u7247\u7684\u683c\u5f0f, \u4f8b\u5982 "jpg"<br>
	 * C type : char[8]
	 */
	public byte[] img_format = new byte[8];
	/**
	 * \u89c6\u9891\u683c\u5f0f\uff0c\u4f8b\u5982 "avi"<br>
	 * C type : char[8]
	 */
	public byte[] video_format = new byte[8];
	/**
	 * \u8f66\u724c\u56fe\u7247\u683c\u5f0f\uff0c\u4f8b\u5982 "jpg"<br>
	 * C type : char[8]
	 */
	public byte[] plate_img_format = new byte[8];
	/**
	 * \u4eba\u8138\u56fe\u7247\u683c\u5f0f\uff0c\u4f8b\u5982 "jpg"<br>
	 * C type : char[8]
	 */
	public byte[] face_img_format = new byte[8];
	/** C type : int[4] */
	public int[] img_time_sec = new int[4];
	/** C type : int[4] */
	public int[] img_time_usec = new int[4];
	/** C type : int[2] */
	public int[] video_start_sec = new int[2];
	/** C type : int[2] */
	public int[] video_start_usec = new int[2];
	/** C type : int[2] */
	public int[] video_end_sec = new int[2];
	/** C type : int[2] */
	public int[] video_end_usec = new int[2];
	/** C type : unsigned short[32] */
	public short[] face_x = new short[32];
	/** C type : unsigned short[32] */
	public short[] face_y = new short[32];
	/** C type : unsigned short[32] */
	public short[] face_w = new short[32];
	/** C type : unsigned short[32] */
	public short[] face_h = new short[32];
	/** C type : unsigned char*[4] */
	public Pointer[] img = new Pointer[4];
	/** C type : unsigned char*[2] */
	public Pointer[] video = new Pointer[2];
	/** C type : unsigned char*[2] */
	public Pointer[] plate_img = new Pointer[2];
	/** C type : unsigned char*[32] */
	public Pointer[] face_img = new Pointer[32];
	public pkg_vehicle() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("sequence_id", "realtime_data", "packet_id", "device_id", "addr_id", "direction_id", "camera_id", "lane_id", "addr_name", "direction_name", "plate", "plate_x", "plate_y", "plate_w", "plate_h", "plate_confidence", "plate_color", "vehicle_style", "vehicle_color", "triger_type", "redlight_begin_sec", "redlight_begin_usec", "system_type", "vio_type", "vehicle_speed", "limit_speed", "recoImageIndex", "vehicle_x", "vehicle_y", "vehicle_w", "vehicle_h", "red_lamp_x", "red_lamp_y", "red_lamp_w", "red_lamp_h", "vio_red_lamp_index", "direction", "reserved", "img_num", "video_num", "plate_img_num", "face_num", "img_len", "video_len", "plate_img_len", "face_img_len", "img_format", "video_format", "plate_img_format", "face_img_format", "img_time_sec", "img_time_usec", "video_start_sec", "video_start_usec", "video_end_sec", "video_end_usec", "face_x", "face_y", "face_w", "face_h", "img", "video", "plate_img", "face_img");
	}
	public static class ByReference extends pkg_vehicle implements Structure.ByReference {
		
	};
	public static class ByValue extends pkg_vehicle implements Structure.ByValue {
		
	};
}
