package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u5e73\u53f0\u53c2\u6570(640\u5b57\u8282)\u3002<br>
 * <i>native declaration : config_gw.h:872</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PlatformParam extends Structure {
	/**
	 * \u670d\u52a1\u3002<br>
	 * C type : PlatformServicesParam
	 */
	public PlatformServicesParam services;
	/**
	 * \u76f8\u673a\u3002<br>
	 * C type : CameraParam
	 */
	public CameraParam camera;
	/**
	 * \u5404\u5e73\u53f0\u53ef\u81ea\u884c\u5b9a\u4e49\u3002<br>
	 * C type : char[112]
	 */
	public byte[] resv = new byte[112];
	public PlatformParam() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("services", "camera", "resv");
	}
	/**
	 * @param services \u670d\u52a1\u3002<br>
	 * C type : PlatformServicesParam<br>
	 * @param camera \u76f8\u673a\u3002<br>
	 * C type : CameraParam<br>
	 * @param resv \u5404\u5e73\u53f0\u53ef\u81ea\u884c\u5b9a\u4e49\u3002<br>
	 * C type : char[112]
	 */
	public PlatformParam(PlatformServicesParam services, CameraParam camera, byte resv[]) {
		super();
		this.services = services;
		this.camera = camera;
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
	}
	public static class ByReference extends PlatformParam implements Structure.ByReference {
		
	};
	public static class ByValue extends PlatformParam implements Structure.ByValue {
		
	};
}
