package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u670d\u52a1(16\u5b57\u8282)\u3002<br>
 * <i>native declaration : config_gw.h:853</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PlatformServicesParam extends Structure {
	/**
	 * \u914d\u7f6e\u670d\u52a1\u53c2\u6570\u3002<br>
	 * C type : ServiceParam
	 */
	public ServiceParam config_service;
	/**
	 * \u6d41\u670d\u52a1\u914d\u7f6e\u53c2\u6570\u3002<br>
	 * C type : ServiceParam
	 */
	public ServiceParam stream_service;
	public PlatformServicesParam() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("config_service", "stream_service");
	}
	/**
	 * @param config_service \u914d\u7f6e\u670d\u52a1\u53c2\u6570\u3002<br>
	 * C type : ServiceParam<br>
	 * @param stream_service \u6d41\u670d\u52a1\u914d\u7f6e\u53c2\u6570\u3002<br>
	 * C type : ServiceParam
	 */
	public PlatformServicesParam(ServiceParam config_service, ServiceParam stream_service) {
		super();
		this.config_service = config_service;
		this.stream_service = stream_service;
	}
	public static class ByReference extends PlatformServicesParam implements Structure.ByReference {
		
	};
	public static class ByValue extends PlatformServicesParam implements Structure.ByValue {
		
	};
}
