package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u5750\u6807\u70b9\u5b9a\u4e49\u3002<br>
 * <i>native declaration : config_gw.h:978</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Point extends Structure {
	public int x;
	public int y;
	public Point() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("x", "y");
	}
	public Point(int x, int y) {
		super();
		this.x = x;
		this.y = y;
	}
	public static class ByReference extends Point implements Structure.ByReference {
		
	};
	public static class ByValue extends Point implements Structure.ByValue {
		
	};
}
