package sdk.facecamera.sdk.sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.FloatByReference;
import java.util.Arrays;
import java.util.List;
/**
 * \u4eba\u8138\u67e5\u8be2\u56de\u8c03\u8fd4\u56de<br>
 * <i>native declaration : FaceRecoDef.h:111</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class QueryFaceInfo extends Structure {
	/** \u67e5\u8be2\u7684\u89d2\u8272\u8bb0\u5f55\u603b\u91cf */
	public int record_count;
	/** \u5f53\u524d\u6536\u5230\u7684\u8bb0\u5f55\u5e8f\u53f7 */
	public int record_no;
	/**
	 * \u4eba\u5458ID<br>
	 * C type : char[20]
	 */
	public byte[] personID = new byte[20];
	/**
	 * \u59d3\u540d<br>
	 * C type : char[16]
	 */
	public byte[] personName = new byte[16];
	/** \u4eba\u5458\u89d2\u8272 0\uff1a\u666e\u901a\u4eba\u5458\u3002 1\uff1a\u767d\u540d\u5355\u4eba\u5458\u3002 2\uff1a\u9ed1\u540d\u5355\u4eba\u5458\u3002 -1\uff1a\u6240\u6709\u4eba\u5458\u3002 */
	public int role;
	/** \u5f53\u524did\u7684\u7279\u5f81\u6570\u603b\u91cf */
	public short feature_count;
	/** \u4eba\u8138\u7279\u5f81\u6570\u636e\u957f\u5ea6 */
	public short feature_size;
	/**
	 * \u4eba\u8138\u7279\u5f81\u6570\u636e\uff0c\u6309\u987a\u5e8f\u6392\u5217\u6240\u6709\u7279\u5f81\u6570\u636e featureSize*feature_count<br>
	 * C type : float*
	 */
	public FloatByReference feature;
	/** \u6a21\u677f\u56fe\u50cf\u6570\u91cf */
	public int imgNum;
	/**
	 * \u56fe\u50cf\u5927\u5c0f\uff0cimgSize[i]\u4e3a\u7b2ci\u5f20\u56fe\u7247\u7684\u5927\u5c0f<br>
	 * C type : int[5]
	 */
	public int[] imgSize = new int[5];
	/**
	 * \u56fe\u50cf\u683c\u5f0f,imgFmt[i]\u4e3a\u7b2ci\u5f20\u56fe\u7247\u7684\u683c\u5f0f<br>
	 * C type : char[5][4]
	 */
	public byte[] imgFmt = new byte[((5) * (4))];
	/**
	 * imgBuff[i]\u4f4d\u7b2ci\u5f20\u56fe\u7247\u7ed9\u6570\u636e\u9996\u5730\u5740<br>
	 * C type : unsigned char*[5]
	 */
	public Pointer[] imgBuff = new Pointer[5];
	/** \u97e6\u6839\u95e8\u7981\u5361\u53f7 */
	public int wgCardNO;
	/** \u6709\u6548\u671f\u622a\u6b62\u65f6\u95f4\uff0c\u8be5\u4eba\u5458\u4fe1\u606f\u5728\u8be5\u65f6\u95f4\u5185\u6709\u6548,\u4ece1970\u5e741\u67081\u65e50\u65f60\u52060\u79d2\u5230\u622a\u6b62\u65f6\u95f4\u7684\u79d2\u6570\uff080xFFFFFFFF\u8868\u793a\u6c38\u4e45\u6709\u6548\uff0c0\u8868\u793a\u6c38\u4e45\u5931\u6548\uff09 */
	public int effectTime;
	/** \u6709\u6548\u671f\u8d77\u59cb\u65f6\u95f4\uff0c\u8be5\u4eba\u5458\u4fe1\u606f\u5728\u8be5\u65f6\u95f4\u4e4b\u540e\u6709\u6548,\u4ece1970\u5e741\u67081\u65e50\u65f60\u52060\u79d2\u5230\u8d77\u59cb\u65f6\u95f4\u7684\u79d2\u6570\uff080\u8868\u793a\u672a\u521d\u59cb\u5316\uff09 */
	public int effectStartTime;
	public QueryFaceInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("record_count", "record_no", "personID", "personName", "role", "feature_count", "feature_size", "feature", "imgNum", "imgSize", "imgFmt", "imgBuff", "wgCardNO", "effectTime", "effectStartTime");
	}
	public static class ByReference extends QueryFaceInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends QueryFaceInfo implements Structure.ByValue {
		
	};
}
