package sdk.facecamera.sdk.sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : config_gw.h:666</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class reco_extra_info extends Structure {
	public int lane;
	public int diff;
	/** 0 or 1 */
	public int number;
	/** C type : RPlate */
	public RPlate plate;
	public short w;
	public short h;
	public int len;
	/** C type : char* */
	public Pointer imgdata;
	public reco_extra_info() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("lane", "diff", "number", "plate", "w", "h", "len", "imgdata");
	}
	/**
	 * @param number 0 or 1<br>
	 * @param plate C type : RPlate<br>
	 * @param imgdata C type : char*
	 */
	public reco_extra_info(int lane, int diff, int number, RPlate plate, short w, short h, int len, Pointer imgdata) {
		super();
		this.lane = lane;
		this.diff = diff;
		this.number = number;
		this.plate = plate;
		this.w = w;
		this.h = h;
		this.len = len;
		this.imgdata = imgdata;
	}
	public static class ByReference extends reco_extra_info implements Structure.ByReference {
		
	};
	public static class ByValue extends reco_extra_info implements Structure.ByValue {
		
	};
}
