package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : config_gw.h:656</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class RPlate extends Structure {
	/** C type : char[16] */
	public byte[] plate = new byte[16];
	/** 0-\u84dd\u8272 1-\u9ed1\u8272 2-\u9ec4\u8272 3-\u767d\u8272 4-\u7eff\u8272 5-\u7ea2\u8272 6-\u7070\u8272 7-\u7d2b\u8272(KISE) */
	public int plateColor;
	public short plateX;
	public short plateY;
	public short plateW;
	public short plateH;
	public float platerealty;
	public RPlate() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("plate", "plateColor", "plateX", "plateY", "plateW", "plateH", "platerealty");
	}
	/**
	 * @param plate C type : char[16]<br>
	 * @param plateColor 0-\u84dd\u8272 1-\u9ed1\u8272 2-\u9ec4\u8272 3-\u767d\u8272 4-\u7eff\u8272 5-\u7ea2\u8272 6-\u7070\u8272 7-\u7d2b\u8272(KISE)
	 */
	public RPlate(byte plate[], int plateColor, short plateX, short plateY, short plateW, short plateH, float platerealty) {
		super();
		if ((plate.length != this.plate.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.plate = plate;
		this.plateColor = plateColor;
		this.plateX = plateX;
		this.plateY = plateY;
		this.plateW = plateW;
		this.plateH = plateH;
		this.platerealty = platerealty;
	}
	public static class ByReference extends RPlate implements Structure.ByReference {
		
	};
	public static class ByValue extends RPlate implements Structure.ByValue {
		
	};
}
