package sdk.facecamera.sdk.sdk;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : config_gw.h:1169</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SnapshotImage extends Structure {
	/** \u5feb\u7167\u65f6\u95f4\u6233 \u79d2 */
	public int timeStamp_s;
	/** \u5feb\u7167\u65f6\u95f4\u6233 \u6beb\u79d2 */
	public int timeStamp_u;
	/** \u5feb\u7167\u56fe\u50cf\u957f\u5ea6 */
	public int snapImageSize;
	/**
	 * \u5feb\u7167\u56fe\u50cf<br>
	 * C type : unsigned char*
	 */
	public Pointer snapImage;
	public SnapshotImage() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("timeStamp_s", "timeStamp_u", "snapImageSize", "snapImage");
	}
	/**
	 * @param timeStamp_s \u5feb\u7167\u65f6\u95f4\u6233 \u79d2<br>
	 * @param timeStamp_u \u5feb\u7167\u65f6\u95f4\u6233 \u6beb\u79d2<br>
	 * @param snapImageSize \u5feb\u7167\u56fe\u50cf\u957f\u5ea6<br>
	 * @param snapImage \u5feb\u7167\u56fe\u50cf<br>
	 * C type : unsigned char*
	 */
	public SnapshotImage(int timeStamp_s, int timeStamp_u, int snapImageSize, Pointer snapImage) {
		super();
		this.timeStamp_s = timeStamp_s;
		this.timeStamp_u = timeStamp_u;
		this.snapImageSize = snapImageSize;
		this.snapImage = snapImage;
	}
	public static class ByReference extends SnapshotImage implements Structure.ByReference {
		
	};
	public static class ByValue extends SnapshotImage implements Structure.ByValue {
		
	};
}
