package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u76f8\u673a\u7cfb\u7edf\u65f6\u95f4\u4fe1\u606f<br>
 * <i>native declaration : FaceRecoDef.h:63</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SystemTime extends Structure {
	/** \u65f6\u533a */
	public byte time_zone;
	/**
	 * \u65e5\u671f 2017/12/6\uff082017\u5e7412\u67086\u65e5\uff09<br>
	 * C type : char[11]
	 */
	public byte[] date = new byte[11];
	/**
	 * \u65f6\u95f4   17:37:05<br>
	 * C type : char[9]
	 */
	public byte[] time = new byte[9];
	/**
	 * \u4fdd\u7559<br>
	 * C type : char[11]
	 */
	public byte[] resv = new byte[11];
	public SystemTime() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("time_zone", "date", "time", "resv");
	}
	/**
	 * @param time_zone \u65f6\u533a<br>
	 * @param date \u65e5\u671f 2017/12/6\uff082017\u5e7412\u67086\u65e5\uff09<br>
	 * C type : char[11]<br>
	 * @param time \u65f6\u95f4   17:37:05<br>
	 * C type : char[9]<br>
	 * @param resv \u4fdd\u7559<br>
	 * C type : char[11]
	 */
	public SystemTime(byte time_zone, byte date[], byte time[], byte resv[]) {
		super();
		this.time_zone = time_zone;
		if ((date.length != this.date.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.date = date;
		if ((time.length != this.time.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.time = time;
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
	}
	public static class ByReference extends SystemTime implements Structure.ByReference {
		
	};
	public static class ByValue extends SystemTime implements Structure.ByValue {
		
	};
}
