package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u7cfb\u7edf\u7f51\u7edc\u4fe1\u606f<br>
 * <i>native declaration : FaceRecoDef.h:140</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SystemNetInfo extends Structure {
	/**
	 * \u7f51\u5361\u7269\u7406\u5730\u5740<br>
	 * C type : char[18]
	 */
	public byte[] mac_addr = new byte[18];
	/**
	 * \u76f8\u673aip\u5730\u5740<br>
	 * C type : char[16]
	 */
	public byte[] ip_addr = new byte[16];
	/**
	 * \u5b50\u7f51\u63a9\u7801<br>
	 * C type : char[16]
	 */
	public byte[] netmask = new byte[16];
	/**
	 * \u9ed8\u8ba4\u7f51\u5173<br>
	 * C type : char[16]
	 */
	public byte[] gateway = new byte[16];
	/**
	 * \u4fdd\u7559<br>
	 * C type : char[14]
	 */
	public byte[] resv = new byte[14];
	public SystemNetInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("mac_addr", "ip_addr", "netmask", "gateway", "resv");
	}
	/**
	 * @param mac_addr \u7f51\u5361\u7269\u7406\u5730\u5740<br>
	 * C type : char[18]<br>
	 * @param ip_addr \u76f8\u673aip\u5730\u5740<br>
	 * C type : char[16]<br>
	 * @param netmask \u5b50\u7f51\u63a9\u7801<br>
	 * C type : char[16]<br>
	 * @param gateway \u9ed8\u8ba4\u7f51\u5173<br>
	 * C type : char[16]<br>
	 * @param resv \u4fdd\u7559<br>
	 * C type : char[14]
	 */
	public SystemNetInfo(byte mac_addr[], byte ip_addr[], byte netmask[], byte gateway[], byte resv[]) {
		super();
		if ((mac_addr.length != this.mac_addr.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.mac_addr = mac_addr;
		if ((ip_addr.length != this.ip_addr.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ip_addr = ip_addr;
		if ((netmask.length != this.netmask.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.netmask = netmask;
		if ((gateway.length != this.gateway.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.gateway = gateway;
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
	}
	public static class ByReference extends SystemNetInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends SystemNetInfo implements Structure.ByValue {
		
	};
}
