package sdk.facecamera.sdk.sdk;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * \u4e34\u65f6\u53c2\u6570\uff0832\u5b57\u8282\uff09\uff0c\u5e94\u7528\u7a0b\u5e8f\u91cd\u542f\u540e\u5c06\u5931\u6548\u3002<br>
 * <i>native declaration : config_gw.h:862</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TemporaryParam extends Structure {
	/** \u5f00\u5173\u89c6\u9891\u6d41\u3002 */
	public byte enable_video;
	/**
	 * \u5404\u7cfb\u7edf\u81ea\u884c\u5b9a\u4e49\u3002<br>
	 * C type : char[27]
	 */
	public byte[] resv = new byte[27];
	public TemporaryParam() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("enable_video", "resv");
	}
	/**
	 * @param enable_video \u5f00\u5173\u89c6\u9891\u6d41\u3002<br>
	 * @param resv \u5404\u7cfb\u7edf\u81ea\u884c\u5b9a\u4e49\u3002<br>
	 * C type : char[27]
	 */
	public TemporaryParam(byte enable_video, byte resv[]) {
		super();
		this.enable_video = enable_video;
		if ((resv.length != this.resv.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.resv = resv;
	}
	public static class ByReference extends TemporaryParam implements Structure.ByReference {
		
	};
	public static class ByValue extends TemporaryParam implements Structure.ByValue {
		
	};
}
