package sdk.facecamera.sdk.sdk;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : HASdkDef.h:262</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class WifiSignal extends Structure {

    public byte[] ssid = new byte[36]; // wifi名称
    public int frequency; // 频率 2.4G或5G
    public int rssi;                // 信号强度 信号强度在[-126, 0]范围递增，频率为5G时[156, 200)递增
    public byte[] mac = new byte[20];// MAC地址
    public byte[] encryptMethod = new byte[256]; // 加密方式
    public int speed;

    public WifiSignal() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("ssid", "frequency", "rssi", "mac", "encryptMethod","speed");
    }

    public static class ByReference extends WifiSignal implements Structure.ByReference {

    }

    ;

    public static class ByValue extends WifiSignal implements Structure.ByValue {

    }

    ;
}
